4 fan control
LexxPluss/LexxHard-ChargingBoard-Firmware pull request #5
Opened 2022-09-27 13:46 UTC by shujima

ファンを動かせるようにしました。

2022-09-28 05:43 UTC, tunefs requested changes
コメント行2行削除できるならお願いしたいです。

2022-09-28 05:43 UTC, tunefs commented on lexxpluss_main.cpp
> +                //digitalWrite(PIN_FAN, 1);
このコメント行不要なら削除したいです。

2022-09-28 05:43 UTC, tunefs commented on lexxpluss_main.cpp
> +                //digitalWrite(PIN_FAN, 0);
ここのコメント行も不要なら削除したいです。

2022-09-29 09:55 UTC, shujima commented
コメント合計3行を削除しました。

2022-09-30 07:03 UTC, tunefs approved these changes
LGTM.

2022-09-30 07:03 UTC, merged

2022-10-03 04:42 UTC, shujima commented
LGTMありがとうございます！
人生初プルリク、人生初マージです！